# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"L\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\")\n\x0bJoinRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\"(\n\tJoinReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0eHistoryRequest\x12\x0c\n\x04room\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x32\xa1\x01\n\x0b\x43hatService\x12*\n\x04Join\x12\x11.chat.JoinRequest\x1a\x0f.chat.JoinReply\x12\x30\n\x04\x43hat\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x12\x34\n\x07History\x12\x14.chat.HistoryRequest\x1a\x11.chat.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=20
  _globals['_CHATMESSAGE']._serialized_end=96
  _globals['_JOINREQUEST']._serialized_start=98
  _globals['_JOINREQUEST']._serialized_end=139
  _globals['_JOINREPLY']._serialized_start=141
  _globals['_JOINREPLY']._serialized_end=181
  _globals['_HISTORYREQUEST']._serialized_start=183
  _globals['_HISTORYREQUEST']._serialized_end=228
  _globals['_CHATSERVICE']._serialized_start=231
  _globals['_CHATSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
